### ISSUE TITLE
Incompatable with @NONEOFTHEABOVE

### ISSUE THREAD

**Issue by bjcarothers** [jhu-redcap/Multi-Column-Checkboxes#2]
As of REDCap version 14.5.15, `@NONEOFTHEABOVE` no longer works in conjunction with `@COLUMNS`, even if the latter is specified last as instructed.

**Comment by devilsphere** [comment]
Thank you very much for bringing this to my attention. I have adjusted the code base and I am testing against multiple Action Tags, should have an update soon.
